security:
  basic:
    enabled: false

management:
  security:
    enabled: false


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.mkim-service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/



spring:
  cloud:
    config:
      uri: ${vcap.services.mkim-config-server.credentials.uri:http://localhost:8888}
